### ISSUE TITLE
Action fails silently if SLACK_BOT_TOKEN is not set

### ISSUE THREAD

**Issue by gr2m** [slackapi/slack-github-action#10]
### Description

Action fails silently if SLACK_BOT_TOKEN is not set

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 1.15.0

node version: I don't think you should ask that, as it's configured in your own [action.yml](https://github.com/slackapi/slack-github-action/blob/d5d276d7ae0f38f29322b80da9baf985cc80f8b1/action.yml#L17)

OS version(s): ubuntu-latest

#### Steps to reproduce:

```yml
        env:
          SLACK_BOT_TOKEN: ${{ secrets.DOES_NOT_EXIST }}
```

#### Expected result:

Should error with a helpful message

#### Actual result:

No output, success status

#### Attachments:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/39992/130364809-216506ed-a8bc-446a-a487-121dd90e8c0c.png">

**Comment by seratch** [comment]
Thanks again. As with https://github.com/slackapi/slack-github-action/issues/9, the error can be improved by having some validation as part of the action.

**Comment by zimeg** [comment]
With the [`@v2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release a step will now exit with an error if no `token` is included, so be sure to include a token 👻 

```yaml
- name: Post to a Slack channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}  # Here's the aforementioned token 
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      text: "howdy <@channel>!"
```

Going to close this issue with this latest release, but if this step isn't causing errors please feel free to comment or [open another issue](https://github.com/slackapi/slack-github-action/issues/new)! 🙏
