### ISSUE TITLE
Sending a message with blocks fails

### ISSUE THREAD

**Issue by m5kr1pka** [slackapi/slack-github-action#11]
### Description

Support for advanced notification to slack fails.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When using Webhook trigger due to [flatten function](https://github.com/slackapi/slack-github-action/blob/main/index.js#L48 ) action fails is more complex messages.

[flatten(payload)](https://github.com/slackapi/slack-github-action/blob/main/index.js#L48) output:
```
{
  text: 'test',
  'blocks.0.type': 'section',
  'blocks.0.text.type': 'mrkdwn',
  'blocks.0.text.text': 'You have a new request: ',
  'blocks.1.type': 'section',
  'blocks.1.fields.0.type': 'mrkdwn',
  'blocks.1.fields.0.text': '*Type:* Computer (laptop)',
  'blocks.1.fields.1.type': 'mrkdwn',
  'blocks.1.fields.1.text': '*When:* Submitted Aut 10'
}
```

#### Steps to reproduce:
```
- name: Send Slack notification
  uses: slackapi/slack-github-action@v1.15.0
  env:
     SLACK_WEBHOOK_URL:  ***
  with:
     payload: '{"text":"test","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"You have a new request: "}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Type:* Computer (laptop)"},{"type":"mrkdwn","text":"*When:* Submitted Aut 10"}]}]}'
```

#### Expected result:
What you expected to happen
```
**slackBotName**
You have a new request:
Type: Computer (laptop)        When: Submitted Aut 10
```

#### Actual result:

What actually happened
```
**slackBotName**
test
```
