### ISSUE TITLE
missing_text_or_fallback_or_attachments 

### ISSUE THREAD

**Issue by vignesh-desk** [slackapi/slack-github-action#117]
### Description
Error: missing_text_or_fallback_or_attachments
Error: Request failed with status code 400

Include this as part of my github action and received the above error, tried with major versions as well

Read the SLACK_WEBHOOK_URL from my secret

```
- name: Send notify
        uses: slackapi/slack-github-action@v1.16.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
