### ISSUE TITLE
Add support for sending threaded messages

### ISSUE THREAD

**Issue by nothingofuse** [slackapi/slack-github-action#119]
### Description

Would like the ability to send a message into a thread by passing thread-ts from a previous message, with optional flag to broadcast the threaded message to the channel.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
Great idea for an enhancement 👍

**Comment by kuboon** [comment]
You can do it with `"thread_ts"` on payload.

see https://github.com/slackapi/slack-github-action/pull/74#pullrequestreview-903772589

**Comment by robgutsopedra** [comment]
Hey @kuboon, I tried this approach some time ago, and had some issues. Something does not work quite well with the output of the action. Let me explain my situation:
1. First I send the message (which is properly and correctly sent)
```
     -  name: Slack Notification for deployment
        id: slack_notif
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: "{\"text\":\"Manual deployment\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Deployment of X to Y by Z , V1 to V2\"}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
```

2. And then I check the outputs of this previous step: 
```
      - name: Run tests
        run: |-
          echo "Slack message outputs"
          echo "Ts --> " ${{ steps.slack_notif.outputs.ts }}
          echo "thread_ts --> " ${{ steps.slack_notif.outputs.thread_ts }}
          echo "time --> ${{ steps.slack_notif.outputs.time }}"
        id: run_tests
```
          
This is the result: 
![image](https://user-images.githubusercontent.com/101654801/196387665-000de024-fa27-420b-a0b7-e1a0c4905f1b.png)

As you can see, there is no thread_ts nor ts which could help me send a threaded message. 

Checking the code of the action itself, I see thread_ts or ts are only outputed in this scenario: 

```
 if (webResponse && webResponse.ok) {
      core.setOutput('ts', webResponse.ts);
      // return the thread_ts if it exists, if not return the ts
      const thread_ts = webResponse.thread_ts ? webResponse.thread_ts : webResponse.ts;
      core.setOutput('thread_ts', thread_ts);
    }
```

And webResponse is only used IF bot_token is being used, never when using INCOMING_WEBHOOK / SLACK_WEBHOOK_URL

```
if (typeof botToken !== 'undefined' && botToken.length > 0) {
      const message = core.getInput('slack-message') || '';
      const channelIds = core.getInput('channel-id') || '';
      const web = new WebClient(botToken);

      if (channelIds.length <= 0) {
        console.log('Channel ID is required to run this action. An empty one has been provided');
        throw new Error('Channel ID is required to run this action. An empty one has been provided');
      }

      if (message.length > 0 || payload) {
        const ts = core.getInput('update-ts');
        await Promise.all(channelIds.split(',').map(async (channelId) => {
          if (ts) {
          // update message
            webResponse = await web.chat.update({ ts, channel: channelId.trim(), text: message, ...(payload || {}) });
          } else {
          // post message
            webResponse = await web.chat.postMessage({ channel: channelId.trim(), text: message, ...(payload || {}) });
          }
        }));
      } else {
        console.log('Missing slack-message or payload! Did not send a message via chat.postMessage with botToken', { channel: channelIds, text: message, ...(payload) });
        throw new Error('Missing message content, please input a valid payload or message to send. No Message has been send.');
      }
    }
```
