### ISSUE TITLE
setting update-ts causes channel_not_found error

### ISSUE THREAD

**Issue by peterhriser** [slackapi/slack-github-action#125]
### Description

Updating comments not working, just returns `channel_not_found` error

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When trying to make a status comment and then update it, I repeatedly encounter "channel_not_found" errors when I have `update-ts` enabled. Removing the `update-ts` flag allows both messages through.

I have these permissions set: 

```
 runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
```
I have the following github action steps:
```
      - id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "test"
          slack-message: "starting test"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      - run: sleep 10
      - uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "test"
          update-ts: ${{ steps.slack.outputs.ts }}
          slack-message: "updated test"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
```

This reliably fails for me with error described above. 
#### Reproducible in:

package version: 1.21.0

OS version(s): ubuntu-latest

#### Steps to reproduce:

1. Run github action with update-ts set to output of previous step

#### Expected result:
I expect this to update the existing message on Slack. 

#### Actual result:

Fails to find channel (message?)

#### Attachments:
![image](https://user-images.githubusercontent.com/43995242/188717646-42e29d0a-2aab-4063-813f-2c5f23ffd565.png)
