### ISSUE TITLE
How to mention whole channel on send message

### ISSUE THREAD

**Issue by jiwidi** [slackapi/slack-github-action#129]
### Description

How can i mention an channel from a send message action? I tried hardwriting the `@channel` but it wont work.

```
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: 'ID'
          slack-message: "mention @channel"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SL}}
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion
