### ISSUE TITLE
Consider Offering One or More Default Messages or Templates

### ISSUE THREAD

**Issue by Kurt-von-Laven** [slackapi/slack-github-action#2]
### Description

One thing I miss about CircleCI is the convenience of issuing Slack notifications. [Their Slack orb](https://github.com/CircleCI-Public/slack-orb) has a few message templates that meet basic needs. It would be ideal to offer some sort of generic starting point. There has been [an explosion of community-contributed Slack notification GitHub actions](https://github.com/marketplace?type=actions&query=slack) that may serve as a reference. I suspect the absence of a default message is the major deficiency of the official Slack GitHub Action that has led to its unpopularity relative to unofficial actions like [rtCamp's](https://github.com/marketplace/actions/slack-notify).

### What type of issue is this?
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Workarounds

Presently, we copy and paste the following pair of steps into each pertinent workflow:
```yaml
      - name: Configure Slack notification.
        if: always()
        run: source ./.github/scripts/setSlackMessage.sh "${{ job.status }}"
      - name: Send Slack notification.
        if: always()
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: ${{ env.SLACK_MESSAGE }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

Here are the contents of `.github/scripts/setSlackMessage.sh`, which we copy into each pertinent repository:
```bash
 #!/bin/bash

set -e -u -f -o pipefail

# Sets the environment variable SLACK_MESSAGE to a string appropriate to send at
# the end of a workflow triggered by a pull_request or push event. Includes the
# given final status of the job in the message.
function setSlackMessage() {
  local repository_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
  local repository_link="<$repository_url|$GITHUB_REPOSITORY>"

  local workflow_url="$repository_url/actions/runs/$GITHUB_RUN_ID"
  local workflow_link="<$workflow_url|$GITHUB_WORKFLOW workflow>"

  local branch="${GITHUB_REF#refs/*/}"
  local pull_request_number event_info event_url
  if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
    pull_request_number="${branch%/*}"
    branch="$GITHUB_HEAD_REF"
    event_url="$repository_url/pull/$pull_request_number"
    event_info="<$event_url|#$pull_request_number> from"
  elif [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
    event_url="$repository_url/commit/$GITHUB_SHA"
    event_info="push of <$event_url|$GITHUB_SHA> to"
  else
    event_url="https://docs.github.com/en/actions/reference/events-that-trigger-workflows#$GITHUB_EVENT_NAME"
    event_info="unexpected <$event_url|$GITHUB_EVENT_NAME> event"
  fi

  local branch_url="$repository_url/commits/$branch"
  local branch_link="<$branch_url|$branch>"

  local slack_message="$workflow_link *$1* for $event_info $branch_link on $repository_link by $GITHUB_ACTOR."
  echo "SLACK_MESSAGE=$slack_message" >>"$GITHUB_ENV"
}

setSlackMessage "$@"
```
