### ISSUE TITLE
💡 Allow `"` on PR Title and not breaking JSON payload

### ISSUE THREAD

**Issue by miquelrossello** [slackapi/slack-github-action#202]
### Description

When using `"` on a Pull Request title the JSON payload is broken.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When placing a `"` on the Pull Request title, for example `Add new field "image"`, the JSON payload gets broken.

#### Reproducible in:

package version: action version v1.23.0

node version:

OS version(s):

#### Steps to reproduce:

1. Add `"` to Pull Request title
2. Execute GH Action and expect to fail

#### Expected result:

Be able to place `"` on Pull Request title without breaking JSON payload.

#### Actual result:

JSON payload is broken.

Console error:
```
Run slackapi/slack-github-action@v1.23.0
Error: Error: Need to provide valid JSON payload
passed in payload was invalid JSON
```

#### Attachments:

Our current use of this GitHub Action from we get this issue.

```yml
name: Notifying slack
on:
  pull_request:
    types: [ labeled ]
jobs:
  notify-slack:
    runs-on: small
    if: ${{ github.event.label.name == 'slack-notification'}}
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "repository": "${{ github.repository }}",
              "pull_request_username": "${{ github.event.pull_request.user.login }}",
              "pull_request_title": "${{ github.event.pull_request.title }}",
              "pull_request_url": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
```

A possible fix for this could be having something like this following workflow but inside the GitHub Action.

```yml
name: Notifying slack
on:
  pull_request:
    types: [ labeled ]
jobs:
  variables:
    outputs:
      pr_title: ${{ steps.var.outputs.pr_title}}
    runs-on: small
    steps:
      - name: Setting global variables
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            core.setOutput('pr_title', '${{ github.event.pull_request.title }}'.replaceAll(/[/"]/g, '\''));
  notify-slack:
    needs: [variables]
    runs-on: small
    if: ${{ github.event.label.name == 'slack-notification'}}
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "repository": "${{ github.repository }}",
              "pull_request_username": "${{ github.event.pull_request.user.login }}",
              "pull_request_title": "${{ needs.variables.outputs.pr_title }}",
              "pull_request_url": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

```

**Comment by e-zim** [comment]
Hey @miquelrossello, thanks for raising this! 👋

I can confirm this behavior still exists on `v1.24.0` and it seems unexpected to me... Quotes in a PR title shouldn't be causing the action to fail, so going to call this a bug.

Your workaround is really solid, but I hope this can be handled automatically by the action instead. We'll look into a fix for this for the next release, but for now, let's keep this issue open.

Really appreciate your details on the issue and the workaround you shared!

**Comment by miquelrossello** [comment]
Thanks @e-zim! If you need any help with this you can count on me.

**Comment by jrehwaldt** [comment]
One possible idea would be to provide the possibility to specify `payload` as yml map instead of text and do the jsonifying inside the slack action. For complex structures the current approach can still be supported allowing the user to pass arbitrary json formatted text, for easy cases the following may do:

```yml
payload:
  repository: ${{ github.repository }}
  pull_request_username: ${{ github.event.pull_request.user.login }}
  pull_request_title: ${{ github.event.pull_request.title }}
  pull_request_url: ${{ github.event.pull_request.html_url }}
```

Not sure if this is doable with GitHub actions?

**Comment by zimeg** [comment]
@jrehwaldt this is a really solid suggestion but we might avoid defining specific inputs since these can be fairly arbitrary. I think it'd be great if a YAML or JSON could be accepted directly as input, but these don't seem to be [supported types](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype) at this time.

Since the `payload` is accepted as a string from within the action, there's no obvious way to fix invalid JSON. Solutions I tried involved catching errors while parsing and lots of regex, but this seemed excessively complex. It also looks like [someone else has tried this](https://kevinquinn.fun/blog/a-real-world-solution-to-escape-embedded-double-quotes-in-json/) with the same goal in mind!

A more simple solution can be [achieved from the calling workflow](https://stackoverflow.com/a/72256930) by wrapping problematic events with `toJSON`. An updated `payload` might then look like:

```yaml
        with:
          payload: |
            {
              "repository": "${{ github.repository }}",
              "pull_request_username": "${{ github.event.pull_request.user.login }}",
              "pull_request_title": ${{ toJSON(github.event.pull_request.title) }},
              "pull_request_url": "${{ github.event.pull_request.html_url }}"
            }
```

The `toJSON` function will automatically escape quotes and wrap the value with double quotes for safe use in the payload.

Since this workaround can be applied from within the action step I'll go ahead and close this issue, but please feel free to continue any discussion here or in another issue. Thank y'all for all of the feedback and suggestions on this!
