### ISSUE TITLE
Ability to use github secret for payload (with variables)

### ISSUE THREAD

**Issue by jprecuch** [slackapi/slack-github-action#214]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I want to use something like this
```
    - name: Send notifications to Slack
        id: slack-notifications
        if: inputs.slack-notifications && always()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        with:
          channel-id: ${{ inputs.slack-notifications-channel }}
          payload: ${{ secrets.SLACK_PAYLOAD}}
 ```
 Payload
 ```
             {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.ICON }} *${{ env.VALIDATION_RESULT }}* - ${{ github.event.action }}${{ github.event.head_commit.message }} on *${{ env.K8S_SERVICE }}* !"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*API-tests:* sucessfull *${{ env.TESTS_SUCESS }}*, failed *${{ env.FAILED_TESTS }}*"
                    }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Github Workflow",
                        "emoji": true
                    },
                     "url": "https://redacted.com/${{ github.run_id }}"
                    },
                    {
                     "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "JIRA issues",
                        "emoji": true
                      },
                      "url": "https://redacted.com/${{ inputs.sde-version }}"
                    },
                    {
                     "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "API report",
                        "emoji": true
                      },
                      "url": "${{ env.API_REPORT }}"
                    },
                    {
                     "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "API logs",
                        "emoji": true
                      },
                      "url": "${{ env.API_TEST_LOGS }}"
                    }
                  ]
                }
              ]
            }
 ```
However if I put any of the json which I generate by Slack builder to github secrets it won't work by default and slack-github-action will end with error. Also it won't replace the variables mentioned in payload at all.
Would it be possible to somehow fix/enhance this? Or write some simple documentation to make this work?

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1. Create github action
2. Add secret to github secrets
3. Monitor logs

#### Expected result:

The notificationd str sent to Slack

#### Actual result:

Error thrown by github action

**Comment by seratch** [comment]
If I understand correctly, enabling to use env variables / inputs inside `secrets.SLACK_PAYLOAD` requires additional efforts on this GH action package side, which may cause issues if the GitHub Actions platform makes changes in the future. So, I don't think supporting your use case is a straight-forward thing.

**Comment by jprecuch** [comment]
Thanks @seratch 
Would at least `secrets.SLACK_PAYLOAD` or `env.SLACK_PAYLOAD` be possible to implement? without variables support?
```
        with:
          channel-id: ${{ inputs.slack-notifications-channel }}
          payload: ${{ secrets.SLACK_PAYLOAD}}
```

**Comment by seratch** [comment]
Didn't it work? As long as the value is a string value, I am not sure why it cannot work. 

Aside from that, my personal opition is that using `payload-file-path` instead should be easier to maintain for you: https://github.com/slackapi/slack-github-action/blob/main/example-workflows/Technique_1_Slack_Workflow_Builder/JSON_payload_from_file.yml Other maintainers may have different opinions, though.

**Comment by jprecuch** [comment]
At the end I used following which works properly. I've stored whole payload to Github variable and let another actions to store it properly to json file.. And those variables I want replaced are specified in env of this action.
```
      - name: Secret to JSON for Slack
        uses: jsdaniell/create-json@v1.2.2
        if: inputs.slack-notifications && always()
        with:
          name: "payload-slack-content.json"
          json: ${{ vars.SLACK_PAYLOAD_JSON }}

      - name: Send notifications to Slack
        id: slack-notifications
        if: inputs.slack-notifications && always()
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          # Variables required for vars.SLACK_PAYLOAD_JSON usage
          ACTIONS_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          channel-id: ${{ inputs.slack-notifications-channel }}
          payload-file-path: payload-slack-content.json
```
I will close this issue because this meets criteria and works.
