### ISSUE TITLE
[question] payload and block-kit

### ISSUE THREAD

**Issue by FranciscoKloganB** [slackapi/slack-github-action#244]
### Description

I have defined a GitHub action that successfully sends to our GitHub channel. The Bot being used is the one from the official GitHub App Bot. A partial snippet is available below.

What is the issue then?

The message gets sent in plaintext to the slack channel (see screenshot). Instead of being formatted the way it was formatted on Block Builder Kit.

It is unclear if I need to configure anything on the app to support formatted messages, and if so, what and how

```yml
// Partial snippet of the entire workflow
name: E2E Cypress Tests Production CRON

on:
  schedule:
    - cron: "0/10 8-18 * * 1-5"

jobs:
  slack:
    runs-on: ubuntu-latest
    name: Send E2E Cypress Tests Results to Slack
    steps:
      - name: Publish to slack channel via bot token
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # alerts-prod-error-dp C035F2UL2HW
          channel-id: "C035F2UL2HW"
          slack-message: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Navigator Production E2E CRON Completed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:* ${{ job.status }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

![image](https://github.com/slackapi/slack-github-action/assets/25959244/b1a39776-f9ca-4ee6-83bc-35b1da79001c)

### What type of issue is this? (place an `x` in one of the `[ ]`)

- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [x] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by WilliamBergamin** [comment]
Hi @FranciscoKloganB thanks for writing in 💯 

Have you tried using the `payload` field instead of the `slack-message` see example from [README.md](https://github.com/slackapi/slack-github-action#usage-1)

```yml
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.24.0
  with:
    # Slack channel id, channel name, or user id to post message.
    # See also: https://api.slack.com/methods/chat.postMessage#channels
    channel-id: 'CHANNEL_ID'
    # For posting a rich message using Block Kit
    payload: |
      {
        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
          }
        ]
      }
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```
