### ISSUE TITLE
Get branch name after merging a pull request

### ISSUE THREAD

**Issue by Vanals** [slackapi/slack-github-action#259]
### Description

Did anyone managed to get and to show the branch name of  what was just being merged to main?

#### Expected result:

Notify devs of a failing workflow running on main, and mention the branch related to the commit

**Comment by zimeg** [comment]
👋 Here's an updated example of the above! Gathering [a branch name from pushes](https://stackoverflow.com/a/58035262) might require other methods, but this all depends on your setup and the steps involved.

Going to close this issue, but please feel free to follow up with more questions whenever 👾 

```yaml
name: Share errors from tests after a merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  run:
    name: Merged tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Mock a test failure
        run: exit 1
      - name: Send message into channel
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            "repository": "${{ github.repository }}",
            "pull_request_username": "${{ github.event.pull_request.user.login }}",
            "pull_request_title": ${{ toJSON(github.event.pull_request.title) }},
            "pull_request_branch": "${{ github.event.pull_request.head.ref }}",
            "pull_request_url": "${{ github.event.pull_request.html_url }}",
```
