### ISSUE TITLE
`blocks` key in README payload appears to be ignored

### ISSUE THREAD

**Issue by jdangerx** [slackapi/slack-github-action#261]
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: v1.24.0

node version: ?

OS version(s): Github runner image `ubuntu-22.04`

#### Steps to reproduce:

1. Modify the [payload from the README](https://github.com/slackapi/slack-github-action#usage-1) to differentiate between the `text` content and the `blocks` content:
  ```yaml
- name: test Slack Action
  uses: slackapi/slack-github-action@v1.24.0
  with:
    payload: |
      {
        "text": "Text: GitHub Action build result: ${{ job.status }}",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "Block: GitHub Action build result: ${{ job.status }}"
            }
          }
        ]
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
2. Run the action

#### Expected result:

The message shows two lines, one starting with "Text: ..." and one starting with "Block: ..."

#### Actual result:
The message says "Text: ..." but not "Block: ..."

#### Attachments:

I tried just sending the "blocks" key without the "text" key and got 

```
Error: no_text
```

Also, I found that in [Block Kit Builder, the README payload results in an error](https://app.slack.com/block-kit-builder/T3G39MKDJ#%7B%22text%22:%22GitHub%20Action%20build%20result:%20$%7B%7B%20job.status%20%7D%7D%5Cn$%7B%7B%20github.event.pull_request.html_url%20%7C%7C%20github.event.head_commit.url%20%7D%7D%22,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22GitHub%20Action%20build%20result:%20$%7B%7B%20job.status%20%7D%7D%5Cn$%7B%7B%20github.event.pull_request.html_url%20%7C%7C%20github.event.head_commit.url%20%7D%7D%22%7D%7D%5D%7D) while removing the `text` key makes it render appropriately. Maybe that's related?

**Comment by zimeg** [comment]
Hey @jdangerx! 👋  I think this is caused by a missing `SLACK_WEBHOOK_TYPE` value for the [incoming webhook technique](https://github.com/slackapi/slack-github-action#technique-3-slack-incoming-webhook). Does adding that to the `env` cause the blocks text to appear?

**Comment by jdangerx** [comment]
Aha! Indeed, either setting `SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK` or using a `SLACK_BOT_TOKEN` instead works - thanks for the quick response! Do you think this warrants an update in `README.md` or was it just a case of me not reading closely enough 😅 ? I'm happy to make the docs change if you think that'd be helpful!

**Comment by zimeg** [comment]
Sweet, glad to hear that! And you're totally right that this isn't clear in the `README.md` - feel free to make a change, it'd be really appreciated! 😄

**Comment by zimeg** [comment]
Quite a few changes were made to the [`README`](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#slack-send-github-action) as part of the [`@v2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release, and the `webhook-type` input option was added to make some of the expected outputs more clear 🙏

Sending `blocks` with [incoming webhooks](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-3-slack-incoming-webhook) can now be done with a snippet like so:

```yaml
- name: Post a message in a channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    webhook-type: incoming-webhook
    payload: |
      text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      blocks:
        - type: "section"
          text:
            type: "mrkdwn"
            text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
```

I'll close this issue for now, but please feel free to write back in if other improvements to documentation or other inputs might be made! 📚 ✨
