### ISSUE TITLE
Nested keys in JSON payloads can't be accessed in Slack workflows

### ISSUE THREAD

**Issue by rzumer** [slackapi/slack-github-action#280]
### Description

This repo uses `flat` for flattening JSON arrays, but by default nested keys are delimited with periods. Periods are not allowed in variable fields in Slack workflows, so it's impossible to reference those keys from flattened payloads.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by zimeg** [comment]
Hey @rzumer! 👋 Really solid callout and thanks for sending a fix in for it as well. I can confirm this is a limitation in Workflow Builder and your patch is a solid solution!

I plan to review the changes soon, but as a workaround for now I suggest individually setting these keys at the top-level of the payload. For example:

```yaml
{
  "github_event_name": ${{ github.event_name }},
  "github_repository": ${{ github.repository }}
}
```

**Comment by rzumer** [comment]
Thanks for the quick response. For a few reasons I won't get into, manually mapping the nested keys would get tedious in my workflows. My plan was to build and run it directly from my branch in a custom action (I went through the steps in my test workflow to validate my PR today), but I don't have an urgent need for it, so hopefully if a fix can be released relatively quickly I can avoid that entirely.

**Comment by zimeg** [comment]
> ...manually mapping the nested keys would get tedious in my workflows.

Makes total sense! Checking now to see if the dot notation is something Workflow Builder can support to avoid a possible breaking change for existing workflows that might expect this as a variable input. I think there might be a few out there!

I'll keep ya updated on anything I hear with that. If there aren't plans for dot notation, I think your patch is the way to go 🚀

**Comment by SamuelCox** [comment]
I believe I'm running into this but I'm not sure I'm understanding the workaround.

Given this:

```
name: message-slack
description: Messages the slack channel
inputs:
  message:
    description: The message to put into the channel
    required: true
  slack-channel-id:
    description: The id for the slack channel
    required: true
  slack-team-id:
    description: The id for the slack team
    required: true
  environment:
    description: The environment we are running on
    required: true

runs:
  using: composite
  steps:
    - uses: slackapi/slack-github-action@v1.26.0
      env:
        WORKFLOW_RUN_URL: <secret>
        SLACK_WEBHOOK_URL: <secret>
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK        
      with:
        slack-message: ${{ inputs.message }}
        payload: |
          {
            "text": ${{ inputs.message }}
          }
```
I was getting an error. If I hard code the payload as:
```
payload: |
          {
            "text": "test"
          }
```          
it works

**Comment by zimeg** [comment]
@SamuelCox this seems to be from a different cause to me. This issue is more about payloads with attributes that have objects as values. Things like:

```yaml
      payload: |
        {
          "example": {
            "value": "12"
          }
        }
```

Happy to take look into workaround for your workflow in a new issue, but I'm guessing the variable message isn't being quoted properly so JSON parsing is failing. :thinking: The following might help:

```yaml
      payload: |
        {
          "text": ${{ toJSON(inputs.message) }}
        }
```
