### ISSUE TITLE
Sending formatted release to slack as payload?

### ISSUE THREAD

**Issue by dingo-d** [slackapi/slack-github-action#304]
### Description

I'm trying to send release notes to Slack channel when I create a release on GH using this workflow:

```yml
name: "Post release notes to Slack"

on:
  release:
    types: ["published"]

jobs:
  slack-notify:
    name: "Post release notes to Slack"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send release notes to Slack"
        uses: "slackapi/slack-github-action@v1.25.0"
        with:
          channel-id: "releases"
          payload: |
            {
              "text": "Release notes",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "# Release notes - ${{ github.event.release.tag_name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.release.body }}"
                  }
                },
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

But I keep getting error: `Error: Need to provide valid JSON payload`.

I've tried to wrap the notes in `toJSON`, but got an error. Exposing it as env variable, still got the error. The only way this worked was when I tried:

```yaml
slack-message: "${{ github.event.release.body }}"
```

instead of `payload`, but in that case I get unstyled markdown in my channel.

Is it possible to send the markdown to the channel in Slack and for it to be properly formatted? I am using the action to send the notification about deployment successes or failures on GH, and it works great (also as a payload with a markdown).

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.
