### ISSUE TITLE
Unable to send custom Emojis in message payload

### ISSUE THREAD

**Issue by grndvl1** [slackapi/slack-github-action#311]
### Description

Unable to use custom emojis in a message.   Is there a technique I am missing?  Not sure why I can get this to work with the API but not with this action.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by zimeg** [comment]
Hey @grndvl1 👋 Thanks for writing in about this! This seems unexpected to me, so I'm curious about the method you're using to post the message?

I'm finding that [including custom emojis](https://api.slack.com/reference/surfaces/formatting#emoji) in either `payload` and `slack-message` seem to both work for me, both from a bot token and incoming webhook, so any other details would be helpful for troubleshooting!

**Comment by zimeg** [comment]
👀 Going to close this as stale - the latest [`@v2`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) version is now released! - since you're noticing this works with the API but not this action, though I'm still curious if this continues to happen in the latest release.

For future reference, this step sends a message with custom emoji in the current version:

```yaml
- name: Send a message with custom emoji
  uses: slackapi/slack-github-action@v2.0.0
  with:
    errors: true
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ env.SLACK_CHANNEL_ID }}
      text: "greetings :octocatted:"
```

Please feel free to comment or [open a new issue](https://github.com/slackapi/slack-github-action/issues/new) if this seems to not continue to not work for you. I'd be interested in knowing of errors that might be returned too! 🙏
