### ISSUE TITLE
how does one send a message with a snippet?

### ISSUE THREAD

**Issue by iamstarkov** [slackapi/slack-github-action#337]
### Description

I'd like to send a nice snippet of code in a message instead of markdown code block.

This is what I do now:
<img width="201" alt="Screenshot 2024-09-05 at 13 30 41" src="https://github.com/user-attachments/assets/6024f208-a5b5-4f38-a930-4bd5a13ac307">

This is what I want:
<img width="298" alt="Screenshot 2024-09-05 at 13 31 02" src="https://github.com/user-attachments/assets/6d24aff1-a9a7-4339-acfa-00357a86d616">

Im not quite sure how to do it and will appreciate any guiding

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by zimeg** [comment]
Hi @iamstarkov! 👋 Thanks for sharing the example! The second snippet is showing a file upload with [a specific file type](https://api.slack.com/types/file#types) instead of block kit blocks or other formatting, which isn't yet possible, but it is good to know of some workaround for this right now. 

Support for this is in progress (#333) and also tracked in #92, but let's keep this open since this seems like a useful case to have documented 📚 🙏

**Comment by zimeg** [comment]
This is now possible with the [`@2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release! Details on updating are included with that link, but [a step like so](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#uploading-a-file) might be helpful for sending snippets:

```yaml
- name: Share a file to that channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: files.uploadV2
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      file: "./path/to/api.json"
      filename: "api.json"
```

I'm going to close this issue for now, but please feel free to comment with follow ups or open another whenever! 🙏
