### ISSUE TITLE
Feature Request: Get Slack Username from Email

### ISSUE THREAD

**Issue by thejeff77** [slackapi/slack-github-action#349]
### Description

I was able to do this in Jenkins, and looking for a way to do it in GHA. I need a way to lookup a slack user's username via their email. 

Github actions give context on the committer via email, but obv github doesn't provide slack user data. In order to tag a user directly, being able to lookup the user's slack id so you can tag them or message them directly would be incredibly valuable.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hey @thejeff77 👋🏻 

Thanks for the posting the question - it's a pretty common use-case to try to look up a user based on their email address and totally makes sense that you'd need to do this from our GitHub Action.

Since you've done this in Jenkins, I imagine you're already aware of the Slack API method [users.lookupByEmail](https://api.slack.com/methods/users.lookupByEmail)?

We don't have a slick way of calling this method from the GitHub Action, but we're playing around with a few ideas for you. Hopefully, together we can find a solution for you until `slack-github-action@v2` lands! Expect a follow-up response soon!

**Comment by zimeg** [comment]
@thejeff77 adding to the suggestion of using the [`users.lookupByEmail`](https://api.slack.com/methods/users.lookupByEmail) method, it should be possible to make this call with a `curl` request and scoped token like so:

```yaml
    - name: Find the Slackbot user ID
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data '{"email":"slackbot@example.com"}' \
          https://slack.com/api/users.lookupByEmail
```

Although making use of the response might require a bit of `bash` magic in this step...

As @mwbrooks mentioned, we're chipping away at `@v2` of this GitHub Action which will have [more support](https://github.com/slackapi/slack-github-action/tree/v2-development#technique-2-slack-api-method) for calling Slack API methods and making use of these responses in later steps.

We'll check that this method works well in these updates and will continue to share updates with changes for that version!

**Comment by thejeff77** [comment]
@zimeg looking forward to it!

**Comment by zimeg** [comment]
@thejeff77 👋 the latest [`@v2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) now makes this more concise, and with a few other actions and help from `jq` a workflow might resemble this:

```yaml
name: Messages
on: push
jobs:
  messenger:
    name: Send a direct message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Get the author
        run: |
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "Author email is: $AUTHOR_EMAIL"
          echo "AUTHOR_EMAIL=$AUTHOR_EMAIL" >> $GITHUB_ENV
      - name: Lookup by email
        id: email
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: users.lookupByEmail
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            email: "${{ env.AUTHOR_EMAIL }}"
      - name: Find the user ID
        if: ${{ steps.email.outputs.ok }}
        run: |
          SLACK_USER_ID=$(echo '${{ steps.email.outputs.response }}' | jq -r '.user.id')
          echo "SLACK_USER_ID=$SLACK_USER_ID" >> $GITHUB_ENV
      - name: Send a message
        if: ${{ steps.email.outputs.ok }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ env.SLACK_USER_ID }}
            text: "hello again."
```

The following scopes will have to be added to the token too: `chat:write`, `users:read`, and `users:read.email`

AFAIK `jq` is supported in the default and [latest](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) `ubuntu-latest` runners, but this could of course be replaced by scripts for more intricate parsings. I'm following along with [upcoming changes](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/) but I'm hopeful that this approach will be supported 🙏

Please also let me know if these steps are working alright! I kinda want to keep this issue open for a bit as a reminder to soon document the `jq` parsings in an example, but am open to chatting about these steps 📚
