### ISSUE TITLE
Invalid input! Failed to parse contents of the provided payload. 

### ISSUE THREAD

**Issue by abiddakhani** [slackapi/slack-github-action#357]
### Description

Multilines with special characters in the logs read from $GITHUB_OUTPUT variable results in the following error.  This is working in 1.27.1
 
> Invalid input! Failed to parse contents of the provided payload. 

### What type of issue is this?
- [X] question

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---
#### Steps to reproduce:

Posting the relevent workflow steps:
Suppose a workflow has a simple step as follows:

```yaml
- name: Test
  run: |
    echo "Exiting now"
    exit 1
```

And now I want read the logs of the above failed workflow and for that I use the below steps in a different workflow with the run_id of the above workflow, it results into an error as mentioned above.

```yaml
- name: Get failed job/step logs
  id: fail_msg
  run: |
    error_log=$(gh run view ${{ inputs.run_id }} --log-failed -R ${{ inputs.repo_name }})
    {
    echo 'get_log<<EOF'
    echo "workflow failed with the following error:"
    echo "$error_log"
    echo EOF
    } >> "$GITHUB_OUTPUT"

- name: Post to Slack
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.thisissecret }}
    payload: |
      channel: "${{ inputs.channel-id }}"
      text: "${{ steps.fail_msg.outputs.get_log }}"
```

#### Expected result:

Should send the logs to slack as expected

#### Attachments:

```txt
file:///opt/actions-runner/_work/_actions/slackapi/slack-github-action/v2.0.0
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload
    at Content.getContentPayload (file:///opt/actions-runner/_work/_actions/s
    at Content.get (file:///opt/actions-runner/_work/_actions/slackapi/slack-
    at new Config (file:///opt/actions-runner/_work/_actions/slackapi/slack-g
    at send (file:///opt/actions-runner/_work/_actions/slackapi/slack-github-
    at file:///opt/actions-runner/_work/_actions/slackapi/slack-github-action
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

**Comment by zimeg** [comment]
Hey @abiddakhani 👋  Thanks for sharing your setup - gathering input with `gh` is super interesting!

This error is raised if the provided `payload` can't be parsed in the order of: YAML, "unwrapped" JSON, then JSON. The `payload` you provide seems solid, but the expanded `get_log` output might cause these parsing to fail due to unescaped characters.

An example for the `gh` command might provide an output like this:

```txt
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.2984264Z ##[group]Run npm run test:gen-cov
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.2984869Z [36;1mnpm run test:gen-cov[0m
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.3042401Z shell: /usr/bin/bash -e {0}
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.3042816Z ##[endgroup]
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4330529Z npm error Missing script: "test:gen-cov"
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4331117Z npm error
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4331714Z npm error To see a list of scripts, run:
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4332209Z npm error   npm run
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4343477Z 
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4344894Z npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-11-14T20_38_59_378Z-debug-0.log
Run tests	unit(test): check unit test coverage	2024-11-14T20:38:59.4400807Z ##[error]Process completed with exit code 1.
```

Which has both quotations and colons that'll cause YAML **and** JSON parsers to error 😅  

We can instead use JSON for the provided `payload` with the [`toJSON`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#tojson) function to escape variable inputs while still using the included formatting with a step like this:

```yaml
- name: Post to Slack
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.thisissecret }}
    payload: |
      "channel": "${{ inputs.channel-id }}",
      "text": ${{ toJSON(steps.fail_msg.outputs.get_log) }}
```

Which has the same `payload` details, but in a JSON format without the outermost braces.

After these changes I'm finding that the input `get_log` message sends as expected to the channel! When testing this, I had to re-run the workflow with **debug** mode on to find a few `payload` parsing details 🔍 

Please let me know if the same change seems to work for you! We'll want to make a note on these cases in the `README` if so, but I'm happy to troubleshoot errors with this approach beforehand!
