### ISSUE TITLE
Improve error reporting when action fail to parse correctly the payload

### ISSUE THREAD

**Issue by cedric-appdirect** [slackapi/slack-github-action#359]
### Description

In case of a payload parse error, we get the message `Invalid input! Failed to parse contents of the provided payload.` which is not very specific. It would be great to have a better message that highlight which line is the source of the error.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When the payload is malformed, it result in a parse error message which does not guide us on where to look for to find the problem. It would be great if we could at least have the line where the first error happen.

#### Reproducible in:

package version: latest

node version:

OS version(s):

#### Steps to reproduce:

1. Send a malformed payload
2. Figure out why it is malformed

#### Expected result:

Display the line of the first error found. I understand there is a difficulty with the optimistic detection of the file format (yaml vs json), but it is likely that a yaml file parse with less error when there is a malformed payload with the yaml parser than with the json parser.

#### Actual result:

Just say: `Invalid input! Failed to parse contents of the provided payload.`

**Comment by zimeg** [comment]
Hey @cedric-appdirect 👋  Thanks for raising this issue! I agree we can improve this erroring a bit 🙏

To find the `payload` that's causing these parsing errors, I'll recommend rerunning the failed job with [debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging) enabled. This includes the input `payload` before parsing happens, and a [YAML](https://www.yamllint.com/) or [JSON](https://jsonlint.com/) validator can be used to find edges.

That's not a fix, but might be helpful as this continues to bring confusion. Below are more details towards finding a fix.

---

Right now YAML parsing errors are [included in debug logs](https://github.com/slackapi/slack-github-action/blob/e598089eaef53883a2d9b325e044899548518a03/src/content.js#L74-L75), but **this requires a rerun to view** AFAIK. An attempt of including the caught JSON error `cause` is [included when thrown](https://github.com/slackapi/slack-github-action/blob/e598089eaef53883a2d9b325e044899548518a03/src/content.js#L96-L98) but I'm noticing that this isn't included in the final output:

```txt
file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:93
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload
    at Content.getContentPayload (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:93:1)
    at Content.get (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:28:1)
    at new Config (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/config.js:115:1)
    at send (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/send.js:13:1)
    at file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:1[23](https://github.com/zimeg/pr_targets/actions/runs/11981961769/job/33409143674#step:2:24):5)
```

The YAML parsing errors happening before the above error (which was caused by failed JSON parsing) might match:

```txt
##[debug]Failed to parse input payload as YAML
##[debug]missed comma between flow collection entries (3:5)
```

> Display the line of the first error found ... it is likely that a yaml file parse with less error when there is a malformed payload with the yaml parser than with the json parser.

We should investigate the reason of the disappearing [`cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause) since I believe that can add a lot of clarity to errors:

```txt
SlackError: Invalid input! Failed to parse contents of the provided payload
    at Content.getContentPayload (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/content.js:100:1)
    at Content.get (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/content.js:28:1)
    ... 5 lines matching cause stack trace ...
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  [cause]: SyntaxError: Expected property name or '}' in JSON at position 2
      at JSON.parse (<anonymous>)
      at Content.getContentPayload (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/content.js:98:1)
      at Content.get (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/content.js:28:1)
      at new Config (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/config.js:115:1)
      at send (file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/send.js:13:1)
      at file:///Users/eden.zimbelman/programming/tools/slack-github-action/src/index.js:9:1
      at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
      at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
      at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
}
```

I'm so interested in how the "right" error can be shown here too! To share more context, YAML was introduced for the convenience of writing workflows in the syntax of GitHub Actions, but the Slack API methods best support JSON.

FWIW falling back to the JSON errors feels right to me with the API considerations, but I understand that's not so helpful when it's YAML parsing that raises errors.

You point out well that we might be somewhat limited with the optimistic filetype detection... This might require separate explorations to figure out how to return the error `cause`, then also returning the relevant parsing error.

I'll mark this as a "good first issue" and encourage additional thoughts or PRs, but this is something we'll look into for an upcoming release. Thanks again for calling this out! 🚀

**Comment by shadone** [comment]
It would be great to prioritize this issue, I am struggling to add Slack integration to our GitHub workflow as the example from the [official Slack documentation](https://tools.slack.dev/slack-github-action/sending-techniques/sending-data-slack-incoming-webhook/post-blocks-found-in-file) fails with this same error, and debug logs do not include any additional useful information

```
##[debug]Gathered action inputs: {"errors":false,"method":"","payload":"","payloadDelimiter":"","payloadFilePath":".github/resources/slack-deployment-failure-message.json","payloadTemplated":true,"proxy":null,"retries":"5","token":null,"webhook":"***","webhookType":"incoming-webhook"}

file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:139
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload file
    at Content.getContentPayloadFilePath (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:139:1)
    at Content.get (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:31:1)
    at new Config (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/config.js:115:1)
    at send (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/send.js:13:1)
    at file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

**Comment by shadone** [comment]
Here as additional info from my failure if that helps

<details>
<summary>This workflow file works fine</summary>

```
name: 'Test Slack Notification'

on:
  push:
    branches: [ "slack-notification" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Notify Slack on Failure
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.ALERT_DEV_CHANNEL_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Danny Torrence left a 1 star review for your property."
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Danny Torrence left the following review for your property:"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<https://example.com|*Overlook Hotel*> :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
                accessory:
                  type: "image"
                  image_url: "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg"
                  alt_text: "Haunted hotel image"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Average Rating*: 1.0"
```
</details>

However if I put the same yaml payload into a separate file, then it no longer works:

<details>
<summary>cat .github/workflows/slack-notification.yml</summary>

```
name: 'Test Slack Notification'

on:
  push:
    branches: [ "slack-notification" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Notify Slack on Failure
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-file-path: .github/resources/test-message.yaml
          payload-templated: true
          webhook: ${{ secrets.ALERT_DEV_CHANNEL_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
```

</details>

<details>
<summary>cat .github/resources/test-message.yaml</summary>

```
text: "Danny Torrence left a 1 star review for your property."
blocks:
  - type: "section"
    text:
      type: "mrkdwn"
      text: "Danny Torrence left the following review for your property:"
  - type: "section"
    text:
      type: "mrkdwn"
      text: "<https://example.com|*Overlook Hotel*> :star: \n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
    accessory:
      type: "image"
      image_url: "https://is5-ssl.mzstatic.com/image/thumb/Purple3/v4/d3/72/5c/d3725c8f-c642-5d69-1904-aa36e4297885/source/256x256bb.jpg"
      alt_text: "Haunted hotel image"
  - type: "section"
    fields:
      - type: "mrkdwn"
        text: "*Average Rating*: 1.0"
```

</details>

<details>
<summary>full error log</summary>

```
##[debug]Evaluating condition for step: 'Notify Slack on Failure'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Notify Slack on Failure
##[debug]Loading inputs
##[debug]Evaluating: secrets.ALERT_DEV_CHANNEL_SLACK_WEBHOOK_URL
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ALERT_DEV_CHANNEL_SLACK_WEBHOOK_URL'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run slackapi/slack-github-action@v2.0.0
  with:
    payload-file-path: .github/resources/test-message.yaml
    payload-templated: true
    webhook: ***
    webhook-type: incoming-webhook
    errors: false
    retries: 5
##[debug]Setting the provided webhook as a secret variable.
::add-mask::***
##[debug]Gathered action inputs: {"errors":false,"method":"","payload":"","payloadDelimiter":"","payloadFilePath":".github/resources/test-message.yaml","payloadTemplated":true,"proxy":null,"retries":"5","token":null,"webhook":"***","webhookType":"incoming-webhook"}

file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:139
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload file
    at Content.getContentPayloadFilePath (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:139:1)
    at Content.get (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:31:1)
    at new Config (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/config.js:115:1)
    at send (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/send.js:13:1)
    at file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Notify Slack on Failure
```
</details>

**Comment by zimeg** [comment]
@shadone Apologies for not catching the errors linked above, but when using `payload-file-path` the contents of a repo need to be checked out beforehand:

```yaml
- name: Checkout the repo
  uses: actions/checkout@v4
  with:
    persist-credentials: false
```

Please let me know if new errors appear after this! We're hoping to soon revisit documentation around various payload inputs to make this more clear, but I hope this can help for now 📚
