### ISSUE TITLE
Feature request: Add support for `icon_emoji` input

### ISSUE THREAD

**Issue by jonathan-saindon** [slackapi/slack-github-action#360]
### Description

Add support for the [icon_emoji](https://api.slack.com/methods/chat.postMessage#arg_icon_emoji) argument of the `chat.postMessage` API method.

This is a small improvements that would help prettify slack messages when sent by github actions.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by zimeg** [comment]
Hey @jonathan-saindon 👋 I agree that sending messages as an emoji can make for interesting messages 🧵 ✨

Both `icon_emoji` and [other arguments](https://api.slack.com/methods/chat.postMessage#args) of `chat.postMessage` (or other Slack API methods) can be included with the `payload` that's sent to the `method`. I'm finding the following step shows as a star when sent:

```yaml
- name: Post a starred message into channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    errors: true
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      icon_emoji: "star"
      text: ":checkered_flag: Action happens at <https://github.com/${{ github.repository }}>"
```

Sending a message [as another author](https://api.slack.com/methods/chat.postMessage#authorship) **does** require an additional `chat:write.customize` scope, which might've blocked these messages beforehand. This can be added to your app from the **OAuth & Permissions** page on [app settings](https://api.slack.com/apps) 📚 

Related to `icon_url` and threaded messages, I also want to note https://github.com/slackapi/bolt-js/issues/1337 still reflects the current behavior and isn't something caused by the API call itself. We don't have updates about changes to this at the moment, but adding a 👍 to the linked issue is helpful as we share this feedback with other teams.

I'll mark this issue as closed for now, and am looking into related documentation improvements, but please feel free to follow up with other suggestions or questions in the meantime! 🙏
