### ISSUE TITLE
Example code misnamed

### ISSUE THREAD

**Issue by rdavison** [slackapi/slack-github-action#361]
### Description

Several examples in the example code have JSON in the filename, but the payload content is actually YAML.

![Screenshot 2024-11-21 at 3 35 23 PM](https://github.com/user-attachments/assets/e29fd0eb-939e-4975-8bd4-ba9317345bbe)

**Comment by zimeg** [comment]
Hey @rdavison 👋  Thanks for catching this - the filenaming might've been missed with recent changes here 😅

We'll update these examples and related documentation super soon to make sure examples like this are clear! 📚

**Comment by zimeg** [comment]
As a quick reference, this example can be written with JSON like so:

```yaml
on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
```
