### ISSUE TITLE
Cannot parse env info in the payload

### ISSUE THREAD

**Issue by duthaho** [slackapi/slack-github-action#37]
### Description

How can I parse the env info to the payload to have the dynamic notification?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] example code related
```
- name: Send notify
        if: steps.changes.outputs.interview == 'true'
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"attachments": [{"color": "#3AA3E3", "author_name": "Pull request submitted by \"${{ env.AUTHOR_NAME }}\"", "title": "\"${{ env.PR_TITLE }}\"", "title_link": "\"${{ env.PR_RUN_LINK }}\""}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          AUTHOR_NAME: $(jq --raw-output .pull_request.user.login $GITHUB_EVENT_PATH)
          AUTHOR_LINK: $(jq --raw-output .pull_request.user.html_url $GITHUB_EVENT_PATH)
          PR_TITLE: $(jq --raw-output .pull_request.title $GITHUB_EVENT_PATH)
          PR_RUN_LINK: $(jq --raw-output .pull_request.html_url $GITHUB_EVENT_PATH)
```
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:
![image](https://user-images.githubusercontent.com/16200755/143688539-6f1ebe2d-5688-4679-99d2-7666bfe14608.png)

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by filmaj** [comment]
Hey @duthaho,

I believe your YAML should tweak how to quote the `payload` property. We actually inject environment variables into the JSON payload to be delivered to the webhook in our GitHub Workflows for this project as part of the integration testing. Check this [line of code out](https://github.com/slackapi/slack-github-action/blob/main/.github/workflows/main.yml#L59):

```
    - name: Post message to Slack via webhook
      id: slackWorkflow
      uses: ./
      with:
        # Workflow builder webhooks need to know the name of the keys in the payload in advance. Without normalizing, the github context payload keys can differ based on the GitHub trigger event type
        # Normalized payload with info pulled out from GitHub trigger event
        payload: "{\"author\":\"${{ github.event.sender.login }}\",\"url\":\"${{ env.URL}}\", \"repoName\":\"${{ github.event.repository.full_name }}\", \"status\":\"${{ job.status }}\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Note that the `payload` is entirely quoted with double-quotes, whereas your example you use single quotes (if I understand correctly, escaping (i.e. `\`) does not work in YAML with single quotes). Maybe give that a shot and see if it works?

**Comment by danturn** [comment]
hi @filmaj i have the same problem, but using a multiline yaml block...

```
    - name: commit-message
      run: echo "COMMIT_MSG=\"$(git log -1 --pretty=format:\"%s\")\"" >> $GITHUB_ENV
    - run: echo "msg: ${{ env.COMMIT_MSG }}"
    - uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |-
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:fire: ${{ github.actor }} broke the ${{ github.workflow }} job :fire:*\n\n${{ env.COMMIT_MSG }}\n${{github.sha}}"
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://tenor.com/view/mochi-mochi-peach-cat-cat-kitty-animated-cry-gif-17774448",
                  "alt_text": "images"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "https://github.com//${{ github.repository}}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
```

so the echo does of `env.COMMIT_MSG` works fine, but i cannot get it to work in the payload, its just empty, output like this:

```
|   '*:fire: nektos/act broke the test job :fire:*\n' +
|     '\n' +
|     '\n' +
|     'd7e9d942ce1d3467bc4012005d4ab19a55d63e28',
```

any advice here?

**Comment by zimeg** [comment]
👋 Hello! Parsing environment variables in payloads was changed somewhat with the [`@v2`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release, and I wanted to share a few changes I noticed with the examples shared here!

@danturn It might be possible that `nektos/act` doesn't have exact support for replacing environment variables between jobs like you're showing. I'm finding the following works in a workflow on GitHub:

```yaml
- name: Sets a commit message
  run: |
    COMMIT_MSG="todo: replace this with a commit"
    echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
```

```yaml
- name: Reports a failure
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      text: "A job failed!"
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: "*:fire: ${{ github.actor }} broke the ${{ github.workflow }} job :fire:*\n\n${{ env.COMMIT_MSG }}\n${{github.sha}}"
          accessory:
            type: image
            image_url: https://media1.tenor.com/m/G8StgJVopSEAAAAd/mochi-mochi-peach-cat-cat.gif
            alt_text: cat
        - type: actions
          elements:
            - type: button
              text:
                type: plain_text
                text: "View Job"
              url: "https://github.com//${{ github.repository}}/actions/runs/${{ github.run_id }}"
```

If this still isn't working after an update, please feel free to [open a new issue](https://github.com/slackapi/slack-github-action/issues/new) with debug logs if possible 🙏 

@duthaho I'm hoping @filmaj found a fix for the initial issue, and am also hoping a YAML approach might make escaping variables more clear going forwards!

Since numerous changes were made since this issue was opened, and a possible fix has been shared, I think we can close this issue for now. Please do comment again if problems persist!
