### ISSUE TITLE
Bug: No longer able to set webhook type via environment variable

### ISSUE THREAD

**Issue by jacob-white-simplisafe** [slackapi/slack-github-action#372]
### Description

Describe your issue here.
After upgrading this action to version 2.0.0 you are no longer able to set the webhook type with an environment variable. I did not see a breaking change not

### What type of issue is this?
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:
2.0.0
node version:
20
OS version(s):
Ubuntu
#### Steps to reproduce:

1. Set up the action with the following code block
```
      - name: Notify failure
        env:
          SLACK_CHANNEL_ID: "<slack channel>"
          CURRENT_DATE: ${{ steps.getCurrentDate.outputs.CURRENT_DATE }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK. 
        uses: slackapi/slack-github-action@v2.0.0
        with:
          payload-file-path: ${{ env.SLACK_FAILURE_PAYLOAD_FILE_PATH }}
```
2. Run it

#### Expected result:

A message is sent using as incoming webhook 

#### Actual result:

Get an error of ` SlackError: Missing input! The webhook type must be 'incoming-webhook' or 'webhook-trigger'.`

#### Attachments:

This could be changed in https://github.com/slackapi/slack-github-action/blob/main/src/config.js#L111 by changing it to `webhookType: core.getInput("webhook-type") || process.env.SLACK_WEBHOOK_TYPE,` which matches the environment variable that previously worked.
https://github.com/slackapi/slack-github-action/blob/74ae656892e6e68e5168be5fb5fc1368a5569b3b/src/slack-send.js#L22-L26

**Comment by zimeg** [comment]
Hey @jacob-white-simplisafe 👋  Thanks for writing in about this!

You're totally right to call this out as a breaking change in `v2.0.0` - the `webhook-type` input is a required input when sending with `webhook`. A [few](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#the-webhook-type-must-be-specified-in-webhook-inputs) [lines](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#the-webhook-type-must-be-specified-for-incoming-webhooks) on this were included in the release notes under breaking changes 📚 

The recommended approach is to now set this value with the step inputs:

```yaml
- name: Notify failure
  uses: slackapi/slack-github-action@v2.0.0
  with:
    payload-file-path: ${{ env.SLACK_FAILURE_PAYLOAD_FILE_PATH }}
    payload-templated: true
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    webhook-type: incoming-webhook
  env:
    CURRENT_DATE: ${{ steps.getCurrentDate.outputs.CURRENT_DATE }}
    SLACK_CHANNEL_ID: "C0123456789"
```

I understand that using `env` to set these values was a convenience from `v1`, and using this environment variable was added after the initial release, but discussions from #221 have pointed us towards `with` to add clarity to the inputs.

Hoping this helps a bit, but I'm curious to know if the updated approach is alright or if `env` can be useful in more cases here. Open to discussing changes if so, so please let me know! 🙏

**Comment by jacob-white-simplisafe** [comment]
Thanks for the clarification!
I read the section of the release notes: 
```
This Action now requires setting the webhook-type as a step input value.
Prior to updating: The webhook type could be omitted to send to Workflow Builder.
Recommended change: Set the webhook-type value to incoming-webhook, as shown in the example below:
```
As it was now required to have the webhook-type set but didn't have to be only supplied with the `with` statement.

For us, env is helpful because we have multiple jobs/steps where we are sending messages, so it was nice to be able to set the webhook type for all the step. A more realistic example for how we use it is

```yaml
on: push

env:
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  SLACK_FAILURE_PAYLOAD_FILE_PATH: <path>

jobs:
   job1:
     steps:
       ### Do stuff
       uses: slackapi/slack-github-action@v2.0.0

   job2:
     steps:
       ### Do stuff
       uses: slackapi/slack-github-action@v2.0.0
   
```

Happy to close this out, if the decision was to require the use of `with`.
