### ISSUE TITLE
Shared environment variables can cause multiple techniques to match which errors

### ISSUE THREAD

**Issue by zimeg** [slackapi/slack-github-action#373]
### Description

Setting either the `SLACK_TOKEN` or `SLACK_WEBHOOK_URL` environment variables for all steps in a workflow, then creating a step with an opposite technique, causes the step to fail despite the input seeming correct. Noted here: https://github.com/slackapi/slack-github-action/issues/372#issuecomment-2518975584

### What type of issue is this?

- [x] bug

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Steps to reproduce:

```yaml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Start a workflow with a webhook trigger
        uses: slackapi/slack-github-action@v2.0.0
        with:
          errors: true
          webhook: ${{ secrets.SLACK_WEBHOOK_TRIGGER }}
          webhook-type: webhook-trigger
          payload: |
            author: ${{ github.event.sender.login }}
```

#### Expected result:

The provided `webhook` input to be used!

#### Actual result:

```
SlackError: Invalid input! Either the token or webhook is required - not both.
```
