### ISSUE TITLE
Multi-line JSON arrives as a single line

### ISSUE THREAD

**Issue by dbeilin** [slackapi/slack-github-action#377]
### Description

I'm trying to send a message by adding a JSON to the markdown block. The JSON itself is a multi-line JSON, but the message arrives as a single-line

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

I have this composite action to send Slack messages:

```yaml
name: "Slack Notification"
description: "Send Slack notifications for GitHub Actions workflows"

inputs:
  slack_bot_token:
    description: "Slack bot token"
    required: true
  channel_id:
    description: "Slack channel id"
    required: false
    default: "channel"
  message:
    description: "Message to send to Slack"
    required: true
  blocks:
    description: "Optional Slack blocks for advanced message formatting"
    required: false

runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v2.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: "${{ inputs.channel_id }}"
          text: "${{ inputs.message }}"
          blocks:
          ${{ inputs.blocks }}
```

Which I call in this example workflow:

```yaml
name: send-slack

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  send-slack:
    name: send-slack
    runs-on: ubuntu-latest

    steps:
      - name: Create JSON file
        run: |
          echo '{ "added": [], "removed": [] }' > diff.json

      - name: Set output
        id: vars
        run: |
          {
            echo 'DIFF_CONTENT<<EOF'
            jq '.' diff.json
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: echo (debug)
        run: |
          echo "${{ steps.vars.outputs.DIFF_CONTENT }}"

      - name: Notification
        uses: dbeilin/orangutan/composite/send-slack-notification@main
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: "@user"
          message: "message"
          blocks: |
            - type: "section"
              text:
                type: "mrkdwn"
                text: '```${{ steps.vars.outputs.DIFF_CONTENT }}```'
```

My `echo` step shows a multi-line JSON:
![image](https://github.com/user-attachments/assets/ec487a9c-5819-49d6-ac1e-9f0b7d8242e3)

But the message arrives as a single line:
![image](https://github.com/user-attachments/assets/c8bb6ae4-d5f1-406f-bba5-d9017f9763e1)

It might be related to quotes, because when I simply copy and pasted the following payload into the block kit playground it seems to work:

```
{
	"blocks": [
		{
			"type": "section",
			"text": {
				"text": "```{\n  \"added\": [],\n  \"removed\": []\n}```",
				"type": "mrkdwn"
			}
		}
	]
}
```

![image](https://github.com/user-attachments/assets/331e8665-2fc3-42b1-b525-434f3a0cf1df)

- I tried adding `toJSON()` in my markdown block, but it didn't work.
- I tried removing the quotes in the composite: `text: "${{ inputs.message }}"`, but it didn't work as well.

Feel like any other change I make just breaks the payload.

Any help on this would be appreciated :)

**Comment by zimeg** [comment]
Hey @dbeilin! 👋  Thanks for sharing these findings and the setup steps!

I'm finding that this might be a limitation of how unescaped or multiline inputs are provided to steps and `mrkdwn` parsing. This isn't related to composite functions either! A direct use of this Action with JSON inputs prints the same outputs...

<details>
<summary>Reference</summary>

```yaml
uses: slackapi/slack-github-action@v2.0.0
with:
  token: ${{ secrets.SLACK_BOT_TOKEN }}
  method: chat.postMessage
  payload: |
    {
      "channel": ${{ secrets.SLACK_CHANNEL_ID }},
      "text": "message",
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": '```${{ steps.vars.outputs.DIFF_CONTENT }}```'
          }
        }
      ]
    }
```

</details>

We do get a few hints from the **debug** outputs though:

```
##[debug]Gathered action inputs: {"errors":false,"method":"chat.postMessage","payload":"{\n  \"channel\": \"***\",\n  \"text\": \"message\",\n  \"blocks\": [\n    {\n      \"type\": \"section\",\n      \"text\": {\n        \"type\": \"mrkdwn\",\n        \"text\": '```{\n  \"added\": [],\n  \"removed\": []\n}```'\n      }\n    }\n  ]\n}","payloadDelimiter":"","payloadFilePath":"","payloadTemplated":false,"proxy":null,"retries":"5","token":"***","webhook":null,"webhookType":""}
##[debug]Parsed request content: {"values":{"channel":"***","text":"message","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"```{ \"added\": [], \"removed\": [] }```"}}]}}
```

Comparing the provided `payload` and parsed `payload` hints at newlines not being kept for `blocks[0].text.text` despite being included in the provided `payload`. I think that might be due to newlines in `DIFF_CONTENT` not being escaped before it is used as input.

Using [`rich_text`](https://api.slack.com/reference/block-kit/blocks#rich_text) instead of `mrkdwn` can give us multiline preformatted outputs in a composite action though! I'm finding the following changes print the message **with** linebreaks:

```yaml
- name: Notification
  uses: dbeilin/orangutan/composite/send-slack-notification@main
  with:
    slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
    channel_id: "@user"
    message: "message"
    blocks: |
      - type: "rich_text"
        elements:
          - type: "rich_text_preformatted"
            elements:
              - type: "text"
                text: ${{ toJSON(steps.vars.outputs.DIFF_CONTENT) }}
```

Please do let me know if this changes your outputs! Passing these parsed blocks using a composite workflow might be fragile in some cases - mixing YAML `blocks` with a JSON `payload` will not work - but I'm hoping this is alright for most cases 👾

**Comment by dbeilin** [comment]
@zimeg using rich text worked! Thank you 😁

**Comment by andylolz** [comment]
Many thanks for this, both!

I was having the same problem. I found it’s (a bit faffy but still) possible to use the `mrkdwn` type, if you do it like this:

```yaml
uses: slackapi/slack-github-action@v2.0.0
with:
  token: ${{ secrets.SLACK_BOT_TOKEN }}
  method: chat.postMessage
  payload: |
    {
      "channel": ${{ secrets.SLACK_CHANNEL_ID }},
      "text": "message",
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": ${{ toJSON(format('```{0}```', steps.vars.outputs.DIFF_CONTENT)) }}
          }
        }
      ]
    }
```

Don’t know if that’s helpful, but sharing in case.
