### ISSUE TITLE
Cannot use slack-message with incoming webhook.

### ISSUE THREAD

**Issue by marcin-lulek-cint** [slackapi/slack-github-action#39]
Can we have support for using `slack-message` with incoming webhooks. Right now it seems that only `payload` key is supported.
The reason for this request is that for example for Pull Request notifications we ended up sometimes with malformed JSON object.

**Comment by srajiang** [comment]
@marcin-lulek-cint - Thanks for the suggestion and for trying out the Slack Github Action! 🎉 

I'll mark this as a feature enhancement request and have set it for our next milestone release. 

If you have time to make a contribution, we welcome submissions!

**Comment by zimeg** [comment]
👋 With the latest [`@2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release, the provided input payload of incoming webhooks should match other messaging APIs, meaning `text` and `blocks` can be used. [Reference](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-3-slack-incoming-webhook).

This is a breaking change that replaces `slack-message` altogether, meaning an updated step might resemble this:

```yaml
- name: Post a message in a channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
    webhook-type: incoming-webhook
    payload: |
      text: "And a new message is posted."
```

I'll close this issue but am of course open to following up with additional ideas or questions! Thanks too for sharing this suggestion!
