### ISSUE TITLE
Feature request: allow sending blocks json file via bot token

### ISSUE THREAD

**Issue by MeikeMertschFortum** [slackapi/slack-github-action#397]
Hi! 

It seems like since v2.0.0 it is still possible to send a blocks.json via web hook, but no longer via bot token.
What I am looking for is something like

```
- name: Send a saved artifact to a Slack workflow
  uses: slackapi/slack-github-action@v2.0.0
  with:
    payload-file-path: "./blocks.json"
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    channel: ${{ secrets.SLACK_CHANNEL_ID }}
```

In the old versions this was:
```
      - name: Send a saved artifact to a Slack workflow
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload-file-path: "./blocks.json"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

**Comment by WilliamBergamin** [comment]
Hi @MeikeMertschFortum thanks for writing in 💯 

I'm not sure I fully understand this feature request, currently you should be able to define the payload values in an file ([source](https://github.com/slackapi/slack-github-action/blob/aef66158a0aa6f218e8762d953e4b92ab4a9286f/src/content.js#L20C2-L49C4))

example 
```yaml
- name: Post blocks to a Slack channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: C123
      text: "GitHub Action build result: done"
      blocks:
        - type: "section"
          text:
            type: "mrkdwn"
            text: "GitHub Action build result: done"
```
Is equivalent to the following
```json
// payload.json
{
  "channel": "C123",
  "text": "GitHub Action build result: done",
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "GitHub Action build result: done"
      }
    }
  ]
}
```
```yaml
- name: Post blocks to a Slack channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload-file-path: "./payload.json"
    payload-templated: true
```

**Comment by SkyHuk** [comment]
Hey there @WilliamBergamin maybe i can help with an example since its sadly not working on my end aswell, even tho I have a very similar setup like your answer.

In my Actions, I'm downloading a job artifact which i produced in a previous job and for debug purposes print the contents successfully. When trying to use the same way as in your comment to send it, its throwing an Error. All relevant file passages and outputs below:

### Workflow yaml (excerpt)
```yaml
notify-slack-on-success:
  name: Notify Slack on success
  runs-on: ubuntu-latest
  needs:
    - scan
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Vulnerability Scan Results
      uses: actions/download-artifact@v4
      with:
        name: trivy-report
        path: report

    - name: Display structure of downloaded files (debug)
      run: ls -R report

    - name: Display content of downloaded report (debug)
      run: cat report/trivy-report.json

    - name: Send Slack Message of scan results
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload-file-path: "report/trivy-report.json"
        payload-templated: true
```
Using `payload-templated: true` makes no difference to without. I guess since I'm not using any variables in the json that makes sense.

### trivy-report.json (redacted)
Using the following in the Block Kit Builder in the Slack API Docs everything works. Of course only minus the `channel` and `text` properties. I guess thats because it only tests the payloads with "blocks" as an element and marks everything else as faulty? Or might this be the error?
```json
{
  "channel": "C08...",
  "text": "blub",
  "blocks": [
    {
      "type": "header",
      "text": {
        "type": "plain_text",
        "text": "Trivy Report - (redacted project name)",
        "emoji": true
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "Project: `(redacted project name)`"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Type: alpine*"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Target: (redacted project name)*"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "_No vulnerabilities found_"
      }
    },
    {
      "type": "divider"
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Type: jar*"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Target: Java*"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "_No vulnerabilities found_"
      }
    },
    {
      "type": "divider"
    },
  ]
}
```

### thrown Error in the action
```
file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:139
      throw new SlackError(
^
SlackError: Invalid input! Failed to parse contents of the provided payload file
    at Content.getContentPayloadFilePath (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:[13](Action job run URL/blub#step:6:13)9:1)
    at Content.get (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/content.js:31:1)
    at new Config (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/config.js:1[15](Action job run URL/blub#step:6:15):1)
    at send (file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/send.js:13:1)
    at file:///home/runner/work/_actions/slackapi/slack-github-action/v2.0.0/src/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:1[17](Action job run URL/blub#step:6:17):5)
```

Do you have any ideas on how to resolve this? I will gladly try them all out. In a previous Job stage before the named "notify-slack-on-success" I'm successfully sending a message, but via `payload` and not `payload-file-path`.

**Comment by zimeg** [comment]
👋 @SkyHuk Thanks for sharing the example `.json` file input 📚

> I guess thats because it only tests the payloads with "blocks" as an element

This might be getting at the problem! I noticed when I copied these example `blocks` into [Block Kit Builder](https://app.slack.com/block-kit-builder/#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Trivy%20Report%20-%20(redacted%20project%20name)%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Project:%20%60(redacted%20project%20name)%60%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Type:%20alpine*%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Target:%20(redacted%20project%20name)*%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22_No%20vulnerabilities%20found_%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Type:%20jar*%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Target:%20Java*%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22_No%20vulnerabilities%20found_%22%7D%7D,%7B%22type%22:%22divider%22%7D%5D%7D) was the trailing comma of the last block was removed:

```diff
    {
      "type": "divider"
-   },
+   }
```

And I'm wondering if the script generating these blocks might be including this? A step to check might use this command:

```sh
jq '.' report/trivy-report.json
```

Since I think this might be help locate if the errors in the contents or parsing!

It's also good to know another step is working with a different `payload` which rules a few options out! I'm hoping this is helpful to start, but please let us know if these errors continue 🙏 ✨ 

As a quick note, changes related to #359 might be helpful with this issue 👾

**Comment by zimeg** [comment]
📣 With the latest [`v2.1.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.1.0) release having improved error messages, I'll close this issue for now!

> Maybe there is a possibility to add some uncluttering / cleanup of the provided JSON just syntax wise, to prevent this.

@SkyHuk This is super interesting and we have a simple approach to wrap "unwrapped" JSON but otherwise I am not aware of a nice JSON parser that accepts trailing commas elsewhere...

https://github.com/slackapi/slack-github-action/blob/47b1876080be991b1fc5ff91d384d0042e769e4e/src/content.js#L79-L90

As a troubleshooting step in the meantime, related to `payload-file-path` in particular, I will recommend both checking that a `checkout` step precedes this action **and** toggling "debug" logs on for a re-run to inspect parsed inputs:

```yaml
- name: Checkout the repo
  uses: actions/checkout@v4
  with:
    persist-credentials: false
```

If this does continue to raise unexpected or confusing errors, or if other thoughts or ideas arise, please do feel free to open a new [issue](https://github.com/slackapi/slack-github-action/issues/new) 💌
