### ISSUE TITLE
Feature request: send direct message to a user

### ISSUE THREAD

**Issue by ndeloof** [slackapi/slack-github-action#40]
### Description

slackapi/slack-github-action can be used to send a message to a channel, but not to send message to a user by it's handle (`@ndeloof`)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

package version: v1.16.0

node version: ?

OS version(s): github's ubuntu-latest hosted runner 

#### Steps to reproduce:

1. create github workflow to send notification to a specific user
```yaml
      - name: Notify 
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: '@ndeloof'          
          slack-message: '🦄'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

#### Expected result:

Can send message to user (maybe using a distinct action parameter)

#### Actual result:

UnhandledPromiseRejectionWarning: Error: An API error occurred: channel_not_found

**Comment by stevengill** [comment]
Hey @ndeloof!

Under the hood, we use the chat.postMessage api to send messages into Slack. This API only supports userIDs, not usernames. See https://api.slack.com/methods/chat.postMessage#channels. Usernames can be changed in the client. So we don't recommend using these (the same goes for channel names). That is why our recommendation is to use the IDs instead.

**Comment by srajiang** [comment]
@stevengill - 👋  Reviewing this a bit more. These are the current usage instructions on the README, which do seem to suggest that the desired behavior is possible (i.e. "name to post message"). So perhaps this documentation can be updated if we don't recommend usernames, but rather `user_id`

```
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.16.0
  with:
    channel-id: 'CHANNEL_ID'  # Slack channel id or name to post message. https://api.slack.com/methods/chat.postMessage#channels
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

You should be able to use USER_ID here @ndeloof! See below:
```
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.16.0
  with:
    channel-id: 'USER_ID'
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

Let us know if this solves your issue, if so feel free to close it out!

**Comment by srajiang** [comment]
Submitted a modified feature request to support more clarified naming on fields: #41

**Comment by ageleisha-ms** [comment]
Hi guys, I try to send direct message by User_id, as I understand It should work, but nothing happened.
```
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.16.0
  with:
    channel-id: 'USER_ID'
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```
But if I send it by curl it works:
`curl --location --request POST 'https://slack.com/api/chat.postMessage' \
--header 'Authorization: Bearer ****' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'channel=***' \
--data-urlencode 'text=Test'`

What can be a reason?
