### ISSUE TITLE
Support user-id syntax

### ISSUE THREAD

**Issue by srajiang** [slackapi/slack-github-action#41]
### Description

As suggested in #41, this action could support the following syntax of `user-id` for improved clarity. Currently channel-id accepts either a Slack CHANNEL_ID or USER_ID.
```
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.16.0
  with:
    user-id: 'USER_ID' # currently channel-id field accepts either CHANNEL_ID or USER_ID
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

Related to 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by zimeg** [comment]
🙏  Closing in favor of using `chat.postMessage` to send a DM, released with [`@2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0):

```yaml
- name: Send a direct message
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_USER_ID }}
      text: "Sending all the best"
```
