### ISSUE TITLE
help..  why is this yaml error

### ISSUE THREAD

**Issue by rookieboba** [slackapi/slack-github-action#432]
I Used Debug and this happens

```
# notify-slack-email.yml
name: Notify Slack & Email
on:
  workflow_run:
    workflows: ["FastAPI CI"]
    types: [completed]
jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
      - name: Debug
        run: |
          echo "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL"
      # … 여기에 에러 포인트가 발생하는 run: | 블록 전체를 넣으세요

```

![Image](https://github.com/user-attachments/assets/7facb519-f047-4d18-87d5-acc0d2119ce4)

this is my full yaml. Plz Help!
or It may be because of slack is over 10 years?

As I Don't know well plz help! 

```
# .github/workflows/notify-slack-email.yml
name: Notify Slack & Email

on:
  workflow_run:
    workflows: ["FastAPI CI"]
    types: [completed]

jobs:
  notify:
    name: 결과 알림 (Slack & Email)
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    steps:
      - name: 🐞 Debug: 환경변수 확인
        run: |
          echo "SLACK_WEBHOOK_URL = '$SLACK_WEBHOOK_URL'"
          env | sort

      - name: Slack 알림 (실패)
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "C08PU6GKZA4",
              "attachments": [
                {
                  "color": "#FF0000",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}",
                  "text": "❌ FastAPI CI 실패",
                  "fields": [
                    { "title": "Workflow", "value": "FastAPI CI", "short": true },
                    { "title": "Run #",    "value": "${{ github.event.workflow_run.run_number }}", "short": true },
                    { "title": "Branch",   "value": "${{ github.event.workflow_run.head_branch }}", "short": true }
                  ]
                }
              ]
            }

      - name: Slack 알림 (성공)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "C08PU6GKZA4",
              "attachments": [
                {
                  "color": "#36A64F",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}",
                  "text": "✅ FastAPI CI 성공",
                  "fields": [
                    { "title": "Workflow", "value": "FastAPI CI", "short": true },
                    { "title": "Run #",    "value": "${{ github.event.workflow_run.run_number }}", "short": true },
                    { "title": "Branch",   "value": "${{ github.event.workflow_run.head_branch }}", "short": true }
                  ]
                }
              ]
            }

      - name: Email 알림
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port:    ${{ secrets.SMTP_PORT }}
          username:       ${{ secrets.SMTP_USERNAME }}
          password:       ${{ secrets.SMTP_PASSWORD }}
          to:             terranbin@gmail.com
          from:           'GitHub Actions <${{ secrets.SMTP_USERNAME }}>'
          subject:        '[FastAPI][CI 알림] ${{ github.event.workflow_run.conclusion }}'
          body: |
            FastAPI CI 파이프라인이 ${{ github.event.workflow_run.conclusion }} 되었습니다.
            • Repo:   ${{ github.repository }}
            • Run #:  ${{ github.event.workflow_run.run_number }}
            • Branch: ${{ github.event.workflow_run.head_branch }}
            • URL:    https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
```
