### ISSUE TITLE
Markdown not honored

### ISSUE THREAD

**Issue by wesbrownfavor** [slackapi/slack-github-action#440]
Hey folks, I'm trying to send a message with some markdown in it, but its not being honored.

According to the reference these should work?
https://api.slack.com/reference/block-kit/blocks#markdown

Here's my example with inline blocks

```
- name: Announce Release
    uses: slackapi/slack-github-action@v2.1.0
    with:
      webhook: ${{ secrets.MY_SECRET }}
      webhook-type: incoming-webhook
      errors: true
      payload: >
        text: "New Release: Shared Helm Chart: 1.2.3"
        blocks:
          - type: header
            text:
              type: plain_text
              text: ":tada: New Release: Shared Helm Chart: 1.2.3"
          - type: divider
          - type: section
            text:
              type: mrkdwn
              text: "## :notebook: Release notes"
          - type: section
            text:
              type: mrkdwn
              text: Blah
          - type: divider
          - type: section
            text:
              type: mrkdwn
              text: "** :computer: Release URL**"
          - type: section
            text:
              type: mrkdwn
              text: http://my_url.com
```
And this is what it ends up looking like:
![Image](https://github.com/user-attachments/assets/0e0d7437-8462-4131-a773-91b574a4ef58)

I have also tried with a payload file:
GHA
```
- name: Announce Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/slack-releases3'
      uses: slackapi/slack-github-action@v2.1.0
      with:
        payload-file-path: .github/workflows/payload.json
        webhook: ${{ secrets.MY_SECRET }}
        webhook-type: incoming-webhook
        errors: true
```

JSON
```
{
  "channel": "${{ env.SLACK_CHANNEL_ID }}",
  "text": "Messages met made meetings meet",
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "# Slack notifications sound following the most recent commit pushed"
      }
    }
  ]
}
```

Result
![Image](https://github.com/user-attachments/assets/0728733b-8fa7-4aa7-abc2-80c14dccaf08)

I would expect to be able to use **bold** and

# HEADER

and other markdown fun in a block called mrkdwn.

Am I doing something wrong?

**Comment by zimeg** [comment]
Hey @wesbrownfavor! 👋 Thanks for sharing these examples and question 👾 ✨ 

The [`markdown`](https://docs.slack.dev/reference/block-kit/blocks/markdown-block#usage-info) block is somewhat different than other `mrkdwn` or `plain_text` types and should be written as top-level blocks instead:


```yaml
payload: |
  text: "New Release: Shared Helm Chart: 1.2.3"
  blocks:
    - type: header
      text:
        type: plain_text
        text: ":tada: New Release: Shared Helm Chart: 1.2.3"
    - type: divider
    - type: markdown
      text: "## :notebook: Release notes"
    - type: markdown
      text: Blah
    - type: divider
    - type: markdown
      text: ":computer: **Release URL**"
    - type: markdown
      text: "[http://my_url.com](http://my_url.com)"

```

Right now I'm finding that this works well with the `chat.postMessage` method [technique](https://tools.slack.dev/slack-github-action/sending-techniques/sending-data-slack-api-method/#posting-a-message-with-blocks) but is returning unexpected errors with `incoming-webhook` using the same `payload`, though this isn't related to these steps AFAICT 🔍

I'll share this finding with the team because this seems unexpected to me, but I'm also hoping for now this is helpful! Please do let me know if other formatting issues or parsing problems continue in the meantime 🙏
