### ISSUE TITLE
Feat request: Find a message to retrieve its ts

### ISSUE THREAD

**Issue by jacklu97** [slackapi/slack-github-action#445]
Hi all!

I'd like to request a feature that can allow bots to find a message on channels for a given text. In my org we get a daily message for PRs and the use case I see is:
- Look for latest message that contains a given text, for example: "Daily PRs for review"
- Get the ts of that message
- Export it as an output for the step
- Use such ts in another step to send a message, send message to channel if none is given

Hope this makes sense for a next iteration.

Thanks!

**Comment by jacklu97** [comment]
Update on this, found out current implementation can actually do this, it is just a matter of playing with bash tools to get the data you need. Sharing this in case someone else needs it:
```yaml
steps:
      - name: Get all messages in channel
        id: retrieve-messages
        uses: slackapi/slack-github-action@v2
        with:
          method: conversations.history
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            inclusive: true

      - name: Find message with specific text
        id: find-message
        run: |
          MESSAGE=$(echo '${{ steps.retrieve-messages.outputs.response }}' | jq '[.messages[] | select( .text | contains("${{ secrets.DAILY_THREAD_TEXT }}")) | {ts}][0]')
          if [[ "$MESSAGE" == "null" || -z "$MESSAGE" ]]; then
            echo "No message found with the specified text."
            echo "thread_found=false" >> $GITHUB_OUTPUT
          else
            echo "message_ts=$(echo $MESSAGE | jq -r '.ts')" >> $GITHUB_OUTPUT
            echo "thread_found=true" >> $GITHUB_OUTPUT
          fi

      - name: Post message to Thread
        if: ${{ steps.find-message.outputs.thread_found == 'true' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: "This is a message in the thread"
            thread_ts: ${{ steps.find-message.outputs.message_ts }}

      - name: Post message to Channel
        if: ${{ steps.find-message.outputs.thread_found == 'false' }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: "This is a message in the channel"
```
