### ISSUE TITLE
Feat: Support `SLACK_COLOR` with `slack-message`

### ISSUE THREAD

**Issue by norman-zon** [slackapi/slack-github-action#72]
### Description

When using a Slack App and the simple

```
with:
  channel-id: '123456789'
  slack-message: 'My message'
```

Syntax, setting `SLACK_COLOR: ${{ job.status }}` has no effect.

### What type of issue is this?

- [x] enhancement (feature request)

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: slackapi/slack-github-action@v1.18.0'

#### Steps to reproduce:

Setup a job like this:
```
uses: slackapi/slack-github-action@v1.18.0
with:
  channel-id: '123456789'
  slack-message: "My message"
env:
   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
   SLACK_COLOR: ${{ job.status }}
```
 
#### Expected result:

The message specified as `slack-message` gets posted to the channel and has a highlight color according to `job.status`.

#### Actual result:

No coloring is added

#### Attachements
<img width="317" alt="image" src="https://user-images.githubusercontent.com/85173861/157217976-89a1efc3-6670-4a67-860d-acf12b81ccaa.png">
