### ISSUE TITLE
Support response output

### ISSUE THREAD

**Issue by SnowCait** [slackapi/slack-github-action#73]
### Description

Action outputs API response, we can get `thread_ts` value in next steps.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Example

```yml
jobs:
  post:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        id: slack
        with:
          channel-id: '#general'
          slack-message: "Summary"
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: '#general'
          payload: |
            {
              "text": "Details",
              "thread_ts": "${{ fromJSON(steps.slack.outputs.response).ts }}"
            }
```
