### ISSUE TITLE
Escaping newlines

### ISSUE THREAD

**Issue by aspin** [slackapi/slack-github-action#82]
### Description

It doesn't seem to be possible to put newlines in the Slack payload. Of course, I could be wrong/missing something.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: v1.18.0

(Github action)

#### Steps to reproduce:

Here's a sample: I'm trying to write a message to Slack for failed builds with the latest commit message. I've tried doing nothing, and escaping the newlines before putting it in the payload.

```yaml
notify:
    if: ${{ always() && needs.test.result == 'failure' }} # always() seems to be needed
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: slack-prepare
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_MESSAGE_TRIMMED=${COMMIT_MESSAGE//$'\n'/'%0A'}
          echo "::set-output name=commit-message::${COMMIT_MESSAGE}"
      - name: Notify
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "commit_hash": "${{ github.sha }}",
              "developer": "${{ github.actor }}",
              "commit_message": "${{  steps.slack-prepare.outputs.commit-message }}"
            }

```

#### Expected result:

Message to be sent with escaped new lines in the payload, and actual new lines in the slack client.

#### Actual result:

```
with:
    payload: {
    "commit_hash": "d5e25d0d0042"
    "developer": "aspin",
    "commit_message": "fix for spaces
  
  multiline"
  }
  
  env:
    SLACK_WEBHOOK_URL: ***
passed in payload was invalid JSON
Error: Error: Need to provide valid JSON payload
```

**Comment by seratch** [comment]
Hi @aspin, can you try using `\n` instead? If I understand correctly, that'd be the right way to have line breaks in JSON data.

```javascript
{
  "commit_hash": "d5e25d0d0042",
  "developer": "aspin",
  "commit_message": "fix for spaces\n\nmultiline"
}
```

**Comment by aspin** [comment]
I see. The problem at hand was that if the commit message had newlines in it, this action ends up outputting the actual new line, not the newline character. To fix that, I had to run a preparation step to fix it and escape the newline character:

```yaml
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: slack-prepare
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_MESSAGE="$(echo "$COMMIT_MESSAGE" | sed -z 's/\n/\\n/g')"
          echo "::set-output name=commit-message::${COMMIT_MESSAGE}"
      - name: Notify
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "commit_hash": "${{ github.sha }}",
              "developer": "${{ github.actor }}",
              "commit_message": "${{ steps.slack-prepare.outputs.commit-message }}"
            }

```

This now produces the correct output in Slack:

```
@here The latest merge (...) to develop for `repo` seems to have broken builds. aspin, please investigate the changes.
Last commit message: multiline fixed
build foobar baz
bahaahha
```

**Comment by eoconnor** [comment]
Hi there! Sorry, I know this issue is closed, but I was hoping I could ask a quick question. I borrowed this solution so that I could post merged PR descriptions in a Slack message, but what I'm finding is that everything after the first line of the description gets dropped. Here's my GitHub action:
```
jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }} == true
    steps:
      - name: Escape newlines in PR description
        id: description-prepare
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          PR_DESCRIPTION="$(echo "$PR_DESCRIPTION" | sed -z 's/\n/\\n/g')"
          echo "::set-output name=pr-description::${PR_DESCRIPTION}"
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            { "text" : "${{ steps.description-prepare.outputs.pr-description }}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
And here's the output of the run:
<img width="560" alt="Screen Shot 2022-06-04 at 9 21 23 AM" src="https://user-images.githubusercontent.com/320359/172015909-0e3f4056-26fe-43c6-bb9a-d6334775be06.png">
Only the first line of the PR description ends up getting posted to the webhook. Any ideas what I did wrong? I'm not very skilled with sed so 🤷‍♂️
