### ISSUE TITLE
Feature Request: be able to post a file to slack

### ISSUE THREAD

**Issue by mccare** [slackapi/slack-github-action#92]
### Description

We are using https://github.com/adrey/slack-file-upload-action to upload a file. Would be great if slackapi would also support this method.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

**Comment by StefanOltmann** [comment]
This would be great!

**Comment by shalva97** [comment]
This is the only feature that is missing for my workflow to be perfect

**Comment by govindgupta1103** [comment]
Is any verified GitHub actions tool available to send the file to Slack? We are not allowed to use unverified tools.

**Comment by shalva97** [comment]
You can use Slack API directly for example:

```yaml
      - name: Upload file to Slack
        run: >
          curl -F file=@app/build/outputs/apk/production/release/app-production-release.apk
          -F "initial_comment=Android production variant APK"
          -F channels=mobile-builds-android
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}"
          https://slack.com/api/files.upload
```

Of course it is not perfect, but it works

**Comment by govindgupta1103** [comment]
Hi Shalva, where  is the file location? Actually I want to attach an artifact which is generated using GitHub actions.

**Comment by shalva97** [comment]
It is specified after @ symbol

> curl -F file=@your-module-here/build/.../app.apk

directory will be your repository url

**Comment by govindgupta1103** [comment]
Hi Shalva, so does this method support only the json files or any other file type. Because I want to upload an excel file to Slack

**Comment by govindgupta1103** [comment]
curl -F file=@app/build/outputs/apk/production/release/app-production-release.apk

Shouldn't file be in double quotes?

**Comment by govindgupta1103** [comment]
Did it work for you Shelva ?

**Comment by shalva97** [comment]
yes, thats what I use in my project. It does not need double queotes. I think its better to ask it somewhere else, because this issue is for a feature request...

**Comment by govindgupta1103** [comment]
Shalva , I know, but the requested feature is posting a file to Slack.  I spent 5 hours today trying to send an excel file using above command but in vain

**Comment by govindgupta1103** [comment]
@srajiang  Can you please confirm if we can send excel file to Slack using the commands provided by @shalva97 .

**Comment by gauravcanon** [comment]
@govindgupta1103  Yes for me it is working fine sending an Excel sheet.

**Comment by govindgupta1103** [comment]
For me too it worked. Thanks

**Comment by unnirapido** [comment]
@seratch would like to contribute to this feature. can I take this up?

**Comment by derekmurawsky** [comment]
I'd love to see this feature added as well. From an implementation perspective, I see it needing to be a two step process to support the nice formatting/block style messages which don't seem to be supported by the upload API (I haven't thoroughly checked this yet, though).  

1. Upload the file generically using the upload API and note the TS
2. Update the message TS with the standard message API, thus supporting blocks.

**Comment by mjrulesamrat** [comment]
It's 2024 and this feature would be a great addition!!

**Comment by amrgetment** [comment]
any updates

**Comment by MatthewCane** [comment]
It looks like this feature is part of the proposed additions to a `v2` of the Action, see #312

**Comment by zimeg** [comment]
👋 Hello! We're so excited to share that as part of the [`@v2.0.0`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) release that @MatthewCane hinted at, this is now possible!

More detailed notes on updating to the latest version are noted in that release and are also in the [`README`](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#slack-send-github-action), but a snippet to upload files might resemble this:

```yaml
- name: Share a file to that channel
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: files.uploadV2
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_CHANNEL_ID }}
      initial_comment: "the results are in!"
      file: "./path/to/results.out"
      filename: "results-${{ github.sha }}.out"
```

With the `files:write` scope attached to the `token`, files should be uploading to the channel your bot has been added to!

For now, we can close this issue, but if anyone is finding issues with file uploads, please feel free to open a new issue 🙏 ✨

**Comment by amrgetment** [comment]
@zimeg I use payload with markdown like the following payload, I wonder how to migrate my json payload to the new version

      - name: 'Post release notes to Slack'
        uses: 'slackapi/slack-github-action@v1.26.0'
        with:
          channel-id: ${{ secrets.SLACK_FILES_CHANNEL_ID }}
          payload: |
            {
            "blocks": [
               {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Release notes*"
                }
              },
               {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.extract_release_note.outputs.release_note }}"
                }
              }
            ]
            }

**Comment by zimeg** [comment]
@amrgetment At a glance that snippet seems to be sending the release notes as a message with perhaps a bot token?

Please let me know if I've misunderstood this setup, but I'd recommend checking out [this example](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#posting-a-message-with-blocks) in the `README` for a change something like:

```yaml
- name: "Post release notes to Slack"
  uses: slackapi/slack-github-action@v2.0.0
  with:
    method: chat.postMessage
    token: ${{ secrets.SLACK_BOT_TOKEN }}
    payload: |
      channel: ${{ secrets.SLACK_FILES_CHANNEL_ID }}
      text: "Release notes have been shared"
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: "*Release notes*"
        - type: section
          text:
            type: mrkdwn
            text: "${{ steps.extract_release_note.outputs.release_note }}"
```

Also note that this includes the bot `token` and the payload also should include a top-level `text` value! I'm hoping this helps, but if let me know if I'm misunderstanding or if something else seems off in [a new issue](https://github.com/slackapi/slack-github-action/issues/new) 🙏
